theme: jekyll-theme-time-machine
title: LadyCaldlow:~#
description:
show_downloads: false
show_repo: false

safe: true

plugins:
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-seo-tag
  - some-other-jekyll-plugin
  
gems:
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap
